<a href="https://colab.research.google.com/github/Parul-gargg/Pandas-Learning/blob/main/PivotTables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Date': pd.date_range('2026-06-01', periods = 20),
    'Product': ['A','B','C','D'] *5,
    'Region': ['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep Month Quarter
0  2026-06-01       A   East    268     95   John  June      Q2
1  2026-06-02       B   West    493     31   Mary  June      Q2
2  2026-06-03       C  North    530     24    Bob  June      Q2
3  2026-06-04       D  South    482     79  Alice  June      Q2
4  2026-06-05       A   East    345     52   John  June      Q2
5  2026-06-06       B   West    619     83   Mary  June      Q2
6  2026-06-07       C  North    591     47    Bob  June      Q2
7  2026-06-08       D  South    118     24  Alice  June      Q2
8  2026-06-09       A   East    699     35   John  June      Q2
9  2026-06-10       B   West    307     37   Mary  June      Q2
10 2026-06-11       C  North    409     71    Bob  June      Q2
11 2026-06-12       D  South    709     19  Alice  June      Q2
12 2026-06-13       A   East    527     56   John  June      Q2
13 2026-06-14       B   West    148     69   Mary  June      Q2
14 2026-06-15       C  North    311     80    Bob  June      Q2
15 2026-06-16       D  South    342     59  Alice  June      Q2
16 2026-06-17       A   East    613     43   John  June      Q2
17 2026-06-18       B   West    753     71   Mary  June      Q2
18 2026-06-19       C  North    827     65    Bob  June      Q2
19 2026-06-20       D  South    729     76  Alice  June      Q2

In [7]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     527.0    NaN    NaN    NaN
North      NaN    NaN  530.0    NaN
South      NaN    NaN    NaN  482.0
West       NaN  493.0    NaN    NaN

In [8]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     490.4    NaN    NaN    NaN  56.2   NaN   NaN   NaN
North      NaN    NaN  533.6    NaN   NaN   NaN  57.4   NaN
South      NaN    NaN    NaN  476.0   NaN   NaN   NaN  51.4
West       NaN  464.0    NaN    NaN   NaN  58.2   NaN   NaN

*Cross Tabs***

In [9]:
pd.crosstab(df['Region'],df['Product']) # crosstab is used for counting functions

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0